// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: models.protobuf

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the protobuf package it is being compiled against.
// A compilation error at this line likely means your copy of the
// protobuf package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the protobuf package
